### ISSUE TITLE
npm install failed - peerDependencies spec need update.

### ISSUE THREAD

**Issue by prasad83** [overlookmotel/sequelize-definer#4]
npm install failed when sequelize-2.0.0-rc8 (latest) was present due to peerDependencies in pacakge.json

```
"peerDependencies": {
    "sequelize": "2.0.0-rc3"
}

**Comment by overlookmotel** [comment]
Yes, I need to update it. I just haven't had a chance to fully test it with more recent versions of Sequelize. Have been going like crazy on another project I'll get onto that in next couple of weeks.

**Comment by overlookmotel** [comment]
Actually, had a spare hour so fixed it just now.

It should work in v0.2.45, just published to npm. @prasad83 Can you possibly give it a go and check it works for you?
